language: php
php:
  - 7.2
dist: xenial
env:
  global:
    - MEMCACHED_HOST=localhost MEMCACHED_PORT=11211
    - REDIS_HOST=localhost REDIS_PORT=6379
  matrix:
    - DB_ENGINE=mysql DB_HOST=localhost DB_USERNAME=root
    - DB_ENGINE=pgsql DB_HOST=localhost DB_USERNAME=postgres
services:
  - mysql
  - postgresql
  - memcached
  - redis-server
before_install:
  - if [ $DB_ENGINE = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE origin;'; fi
  - if [ $DB_ENGINE = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE origin_test;'; fi
  - if [ $DB_ENGINE = 'pgsql' ]; then psql -c 'CREATE DATABASE origin;' -U postgres; fi
  - if [ $DB_ENGINE = 'pgsql' ]; then psql -c 'CREATE DATABASE origin_test;' -U postgres; fi
  - pecl channel-update pecl.php.net
  - echo yes | pecl install -f apcu
  - echo 'extension = apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
before_script:
  - composer install --prefer-source --no-interaction
 script:
   - vendor/bin/phpunit --coverage-clover=clover.xml
cache:
  directories:
    - $HOME/.composer/cache/files
deploy:
  on:
    branch: master
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)