language: php
php:
  - 7.1
  - 7.2
  - 7.3
dist: xenial
env:
  matrix:
    - DB_USERNAME=root DB_ENGINE=mysql DB_HOST=localhost
services:
  - mysql
  - postgresql
before_install:
  - if [ $DB_ENGINE = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE origin;'; fi
  - if [ $DB_ENGINE = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE origin_test;'; fi
before_script:
  - composer install --prefer-source --no-interaction